### PR TITLE
Adjust formatting for gitter purposes

### PR DESCRIPTION
**Pull request by DavidDudson**
This basically is a "best attempt" at improving the return for gitter.

This is under the assumption that this bot is currently only used for gitter channels.

Anything better would require using the gitter REST api and not IRC

### CODE REVIEW

**Comment by OlegYch** [comment]
as a matter of fact it is currently used for IRC too
it should be possible to use this changes only for gitter specific org.multibot.Multibot instance (created in org.multibot.Multibottest)
could you update the pr?

**Comment by DavidDudson** [comment]
Note: I have not tested this yet, as the changes to metabot to handle this are slightly more involved

**Comment by DavidDudson** [comment]
@OlegYch Since you have access to multibot2 would you be able to quickly test this?

**Comment by OlegYch** [comment]
@DavidDudson multibot2 access key is available by default, you can test it with 'sbt run' on https://gitter.im/OlegYch/multibot

**Comment by DavidDudson** [comment]
I literally just realised that. looks good to me

**Comment by DavidDudson** [comment]
Thanks for the quick responses

**Comment by OlegYch** [comment]
deployed, thanks for the contribution

**Pull request merged**
